baseURL = "https://hct.github.io/"
languageCode = "de-at"
title = "Hockey Club Thaur"
theme = "ananke"
[pagination]
pagerSize = 10

[params]
  author = "Hockey Club Thaur"
  description = "Offizielle Homepage des HC Thaur"
